apiVersion : apps/v1
kind: Deployment
metadata:
  name: dgkanatsiosaksdotnet 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgkanatsiosaksdotnet
  template:
    metadata:
      labels:
        app: dgkanatsiosaksdotnet 
    spec:
      containers:
        - name: dgkanatsiosaksdotnet 
          image: testgkanatsios.azurecr.io/dgkanatsiosaksdotnet
          ports:
          - containerPort: 80